name: medicinadireta
description: Medicina Direta - Soluções para Clínicas e Consultórios.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.51+10000071

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.3
  crypto: ^3.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.6.0
  device_info_plus: ^3.2.4
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  flutter_html: ^2.1.0 ## se atualizar para uma acima quebra webview_flutter
  webview_flutter: ^2.0.4 ## se atualizar para uma acima quebra flutter_html
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  mask_text_input_formatter: ^2.3.0
  open_file_safe: ^3.2.3
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1
  url_launcher: ^6.1.3
  transparent_image: ^2.0.0
  internet_connection_checker: ^0.0.1+4
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  html_editor_enhanced: ^2.5.0
  cupertino_icons: ^1.0.2
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  signalr_netcore: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400