const ENDPOINT_PROD = "https://api.medicinadireta.com.br/odata";
const ENDPOINT_INFO_MED_HOM = "https://api-hom.informed.digital";
const ENDPOINT_INFO_MED = "https://api-prod.informed.digital";
const ENDPOINT_ANEXO = "https://api02.medicinadireta.com.br/odata";
const urlWebSocket = "https://api.medicinadireta.com.br:8084/online-app";
const ENDPOINT = ENDPOINT_PROD;
const STATUS_CODE_DEFAULT = 999;
const STATUS_MESSAGE_DEFAULT = "ATENÇÃO!, NÃO FOI POSSIVEL CONCLUIR A REQUISIÇÃO";
const kReleaseDebugAPP = false;
